In [1]:
import sys
import pandas as pd
from pathlib import Path

PROJECT_ROOT = r"c:\Users\msheh\Desktop\SIRA"
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

In [2]:
from src.data_loader import DataLoader
from src.eda import DataExplorer

In [3]:
loader = DataLoader()
explorer = DataExplorer()
df = loader.load_data()

In [4]:
explorer.show_missing_values(df)

report_text    2
reported_by    1
dtype: int64

In [6]:
df

,report_text,location,reported_by
incident_id,,,
1,Pressure leak detected on Pipeline 7.,Pipeline 7,John
2,Worker slipped near drilling platform.,Platform A,Aisha
3,Gas detector triggered alarm.,Plant B,Michael
4,Small oil spill observed near storage tank.,Tank Farm,David
5,Emergency shutdown initiated after abnormal vi...,Refinery,Grace
6,NaN,Pipeline 8,John
7,Pressure leak detected on Pipeline 7.,Pipeline 7,John
8,gas detector triggered alarm.,Plant B,Michael
9,Gas detector triggred alarm.,Plant B,Michael
10,Worker slipped near drilling platform.,Platform A,Aisha
11,NaN,Tank Farm,David
12,PRESSURE LEAK DETECTED ON PIPELINE 7.,Pipeline 7,John
13,Pressure leak detected on Pipeline 7.,Pipeline 7,John
14,Worker slipped near drilling platform.,Platform A,NaN
15,Emergency shutdown initiated after abnormal vi...,Refinery,Grace

In [5]:
df_empty = df[df["report_text"] == ""]
df_empty_count = df_empty.shape[0]
df_empty_count

0

In [8]:
explorer.duplicate_rows(df)

AttributeError: 'DataExplorer' object has no attribute 'duplicate_rows'

In [9]:
df.duplicated()

incident_id
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15     True
dtype: bool

In [10]:
df["report_text"]

incident_id
1                 Pressure leak detected on Pipeline 7.
2                Worker slipped near drilling platform.
3                         Gas detector triggered alarm.
4           Small oil spill observed near storage tank.
5     Emergency shutdown initiated after abnormal vi...
6                                                   NaN
7              Pressure leak detected on Pipeline 7.
8                         gas detector triggered alarm.
9                          Gas detector triggred alarm.
10               Worker slipped near drilling platform.
11                                                  NaN
12                PRESSURE LEAK DETECTED ON PIPELINE 7.
13                Pressure leak detected on Pipeline 7.
14               Worker slipped near drilling platform.
15    Emergency shutdown initiated after abnormal vi...
Name: report_text, dtype: str

In [12]:
repr(df.loc[7, "report_text"])

"'   Pressure leak detected on Pipeline 7.   '"

In [17]:
df["report_text"] = df["report_text"].str.lower()

In [18]:
df

,report_text,location,reported_by
incident_id,,,
1,pressure leak detected on pipeline 7.,Pipeline 7,John
2,worker slipped near drilling platform.,Platform A,Aisha
3,gas detector triggered alarm.,Plant B,Michael
4,small oil spill observed near storage tank.,Tank Farm,David
5,emergency shutdown initiated after abnormal vi...,Refinery,Grace
6,NaN,Pipeline 8,John
7,pressure leak detected on pipeline 7.,Pipeline 7,John
8,gas detector triggered alarm.,Plant B,Michael
9,gas detector triggred alarm.,Plant B,Michael
10,worker slipped near drilling platform.,Platform A,Aisha
11,NaN,Tank Farm,David
12,pressure leak detected on pipeline 7.,Pipeline 7,John
13,pressure leak detected on pipeline 7.,Pipeline 7,John
14,worker slipped near drilling platform.,Platform A,NaN
15,emergency shutdown initiated after abnormal vi...,Refinery,Grace

In [19]:
corrections = {"triggred": "triggered"}

In [22]:
corrections.items()

dict_items([('triggred', 'triggered')])

In [20]:
for wrong, correct in corrections.items():
    df["report_text"] = df["report_text"].str.replace(
        wrong,
        correct,
        regex=False
    )

In [21]:
df

,report_text,location,reported_by
incident_id,,,
1,pressure leak detected on pipeline 7.,Pipeline 7,John
2,worker slipped near drilling platform.,Platform A,Aisha
3,gas detector triggered alarm.,Plant B,Michael
4,small oil spill observed near storage tank.,Tank Farm,David
5,emergency shutdown initiated after abnormal vi...,Refinery,Grace
6,NaN,Pipeline 8,John
7,pressure leak detected on pipeline 7.,Pipeline 7,John
8,gas detector triggered alarm.,Plant B,Michael
9,gas detector triggered alarm.,Plant B,Michael
10,worker slipped near drilling platform.,Platform A,Aisha
11,NaN,Tank Farm,David
12,pressure leak detected on pipeline 7.,Pipeline 7,John
13,pressure leak detected on pipeline 7.,Pipeline 7,John
14,worker slipped near drilling platform.,Platform A,NaN
15,emergency shutdown initiated after abnormal vi...,Refinery,Grace