In [1]:
import sys
import pandas as pd
from pathlib import Path

In [2]:
from src.data_loader import DataLoader
from src.eda import DataExplorer

In [3]:
loader = DataLoader()
explorer = DataExplorer()
df = loader.load_data()

In [4]:
explorer.show_missing_values(df)

report_text    38
location       21
reported_by    26
dtype: int64

In [5]:
df.duplicated()

incident_id
1      False
2      False
3      False
4      False
5      False
       ...
683     True
582     True
351     True
366     True
145     True
Length: 1000, dtype: bool

In [6]:
df["report_text"]

incident_id
1      Pressure leak detected on Pipeline 7 during ro...
2                                                    NaN
3                                                    NaN
4          Smoke observed from electrical control panel.
5                                                    NaN
                             ...
683      Small hydraulic fluid leak found beneath crane.
582      small hydraulic fluid leak found beneath crane.
351    Routine valve maintenance completed without is...
366      Unauthorized personnel entered restricted area.
145     Corrosion observed on external pipeline coating.
Name: report_text, Length: 1000, dtype: str

In [7]:
df.shape

(1000, 9)

In [12]:
df.describe()

,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
count,962,979,974,1000,1000,1000,1000,1000,1000
unique,38,15,15,12,12,11,499,2,4
top,small hydraulic fluid leak found beneath crane.,Flow Station,Ahmed,Production,Medium,Equipment Failure,2026-06-13,Night,Resolved
freq,75,80,77,130,378,206,9,502,261

In [13]:
df["severity"] = df["severity"].str.lower()

In [14]:
df.head()

,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
incident_id,,,,,,,,,
1,pressure leak detected on pipeline 7 during ro...,Platform B,Aisha,Instrumentation,high,Leak,2025-09-30,Day,Open
2,NaN,Compressor Station,Mary,Utilities,low,Inspection,2025-12-15,Day,Closed
3,NaN,Tank Farm,Mary,Utilities,medium,Slip/Fall,2025-09-09,Day,Open
4,smoke observed from electrical control panel.,Refinery,Joy,Production,high,Electrical,2026-01-22,Day,Open
5,NaN,Gas Processing Unit,Samuel,Production,medium,Equipment Failure,2025-02-14,Day,Closed

In [11]:
df.isnull().sum()

report_text      38
location         21
reported_by      26
department        0
severity          0
incident_type     0
report_date       0
shift             0
status            0
dtype: int64

In [15]:
import sys
print(sys.executable)

c:\Users\msheh\Desktop\SIRA\.venv-1\Scripts\python.exe

In [16]:
explorer.duplicate_rows(df)

'number of duplicate rows: 40'

In [18]:
df.head(10)

,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
incident_id,,,,,,,,,
1,pressure leak detected on pipeline 7 during ro...,Platform B,Aisha,Instrumentation,high,Leak,2025-09-30,Day,Open
2,NaN,Compressor Station,Mary,Utilities,low,Inspection,2025-12-15,Day,Closed
3,NaN,Tank Farm,Mary,Utilities,medium,Slip/Fall,2025-09-09,Day,Open
4,smoke observed from electrical control panel.,Refinery,Joy,Production,high,Electrical,2026-01-22,Day,Open
5,NaN,Gas Processing Unit,Samuel,Production,medium,Equipment Failure,2025-02-14,Day,Closed
6,worker slipped on wet surface near loading bay.,Flow Station,Blessing,Pipeline Operations,medium,Slip/Fall,2025-10-26,Night,Resolved
7,oil spill discovered near storage tank.,Wellhead 12,Paul,Pipeline Operations,high,Oil Spill,2025-11-09,Night,Resolved
8,corrosion observed on external pipeline coating.,Control Room,Chinedu,Electrical,medium,Corrosion,2025-11-19,Day,Resolved
9,smoke observed from electrical control panel.,Flow Station,Daniel,Electrical,high,Electrical,2026-03-21,Night,Resolved
10,NaN,Compressor Station,John,Maintenance,medium,Equipment Failure,2025-03-26,Night,Under Investigation

In [26]:
import os
print(os.getcwd())

c:\Users\msheh\Desktop\SIRA

In [25]:
clean_df = pd.read_csv("data/processed/incident_reports_clean.csv")
clean_df.head()

,report_text,location,reported_by,department,severity,incident_type,report_date,shift,status
0,Pressure leak detected on Pipeline 7 during ro...,Platform B,Aisha,Instrumentation,High,Leak,2025-09-30,Day,Open
1,NaN,Compressor Station,Mary,Utilities,Low,Inspection,2025-12-15,Day,Closed
2,NaN,Tank Farm,Mary,Utilities,Medium,Slip/Fall,2025-09-09,Day,Open
3,Smoke observed from electrical control panel.,Refinery,Joy,Production,High,Electrical,2026-01-22,Day,Open
4,NaN,Gas Processing Unit,Samuel,Production,Medium,Equipment Failure,2025-02-14,Day,Closed